import type { GuideLesson, LessonText } from './guideLessons'

export function calculusLesson(t: LessonText): GuideLesson {
  return {
    slug: 'calculus-roadmap',
    title: t('A First Calculus Unit: Limits, Change, and Accumulation', '微积分第一单元：极限、变化与累积'),
    summary: t('Build the connection from nearby function values to instantaneous rates, then from rates to total change.', '从相邻函数值理解瞬时变化率，再从变化率理解总变化量。'),
    level: t('Introductory single-variable calculus', '一元微积分入门'),
    audience: t('For first-time calculus learners who can manipulate algebraic expressions, or learners reviewing the meaning behind the rules.', '适合已能进行代数运算的微积分初学者，也适合希望重新理解公式含义的复习者。'),
    scope: t('Four focused chapters introduce limits, derivatives, the chain rule, and definite integrals with polynomial examples. This is not a complete Calculus I or AP syllabus. Trigonometric, exponential, and logarithmic derivatives, optimization, integration techniques, and series require further study.', '四章内容通过多项式例子介绍极限、导数、链式法则与定积分。本单元不覆盖完整的大学微积分或 AP 课纲；三角、指数、对数函数求导，优化问题、积分技巧与级数仍需进一步学习。'),
    prerequisites: [
      t('Expand a square, factor a difference of squares, and cancel a nonzero common factor.', '能展开平方、分解平方差，并在公因子非零时约分。'),
      t('Evaluate a function, read slope as output change per input change, and state a function’s domain.', '能求函数值，把斜率理解为输出变化量与输入变化量之比，并说明定义域。'),
      t('For a full calculus course beyond this unit, also review trigonometry, exponentials, and logarithms.', '若要继续学习完整微积分课程，还需复习三角函数、指数函数与对数函数。'),
    ],
    goals: [
      t('Distinguish a function’s value at a point from its limit as the input approaches that point.', '能区分函数在某点的值与输入趋近该点时的极限。'),
      t('Derive a simple derivative from a difference quotient and interpret its sign and units.', '能从差商求出简单函数的导数，并解释符号与单位。'),
      t('Differentiate a composite polynomial, write a tangent line, and distinguish net change from total distance.', '能对复合多项式求导、写出切线方程，并区分净变化量与总路程。'),
    ],
    studyPlan: t('Begin with D1 and D2. D3–D5 sample ideas taught later, so unfamiliarity is expected on a first pass. Work through chapters in order if calculus is new; use the weak-area links if reviewing. Keep a written record of units, domain restrictions, and the reason for each limit or derivative step. Attempt answers before revealing them.', '先完成 D1 与 D2。D3–D5 涉及后面才会学习的内容，初学时不会很正常。如果第一次学微积分，按章学习；如果是复习，可按薄弱环节跳转。做题时记录单位、定义域限制，以及每一步极限或求导操作的理由。先作答，再展开答案。'),
    diagnosticIntro: t('D1 checks essential algebra; D2 introduces the first calculus idea. The remaining questions help returning learners choose what to review. These are not prerequisites you must already pass to start.', 'D1 检查必要的代数基础，D2 引出第一个微积分概念，其余题目帮助复习者选择重点。开始学习前，不要求你已经会做所有题。'),
    diagnostic: [
      { id: 'c-d1', prompt: t('D1 · Algebra readiness: simplify for h ≠ 0.', 'D1 · 代数准备：在 h ≠ 0 时化简。'), equation: '\\frac{(x+h)^2-x^2}{h}', answer: '2x + h', explanation: t('Expand (x + h)² = x² + 2xh + h². Subtract x², factor h, then cancel it using h ≠ 0.', '展开 (x + h)² = x² + 2xh + h²。减去 x² 后提取公因子 h，再利用 h ≠ 0 约分。'), commonMistake: t('h comes from omitting the cross term 2xh. If this is difficult, review algebraic expansion before Chapter 2.', '只得到 h，是因为漏掉了交叉项 2xh。如果这里有困难，先复习展开运算，再进入第 2 章。'), reviewChapterId: 'limits' },
      { id: 'c-d2', prompt: t('D2 · Limit versus value: find the limit. Is the original quotient defined at x = 1?', 'D2 · 极限与函数值：求极限。原分式在 x = 1 时有定义吗？'), equation: '\\lim_{x\\to1}\\frac{x^2-1}{x-1}', answer: t('The limit is 2; the original quotient is undefined at x = 1.', '极限为 2；原分式在 x = 1 时无定义。'), explanation: t('For x ≠ 1, factor and cancel to obtain x + 1. Nearby outputs approach 2 from both sides, even though the original rule has no value at 1.', '当 x ≠ 1 时，因式分解并约分可得 x + 1。两侧的邻近输出都趋近 2，尽管原规则在 1 处无值。'), commonMistake: t('“0/0, so the limit is zero” is invalid. 0/0 is not a number; it tells you direct substitution has not settled the limit.', '“0/0，所以极限为零”不成立。0/0 不是一个数，它只是说明直接代入不能确定极限。'), reviewChapterId: 'limits' },
      { id: 'c-d3', prompt: t('D3 · Meaning of a derivative: a tank’s volume V is measured in liters and time in minutes. What do V(2) = 7 and V′(2) = −3 mean?', 'D3 · 导数含义：水箱体积 V 以升计，时间以分钟计。V(2) = 7 与 V′(2) = −3 分别表示什么？'), answer: t('At 2 minutes the volume is 7 liters and is decreasing instantaneously at 3 liters per minute.', '在第 2 分钟，水量为 7 升，并且当时正以每分钟 3 升的瞬时速率减少。'), explanation: t('The function value measures an amount. Its derivative measures the local rate of change of that amount, so the derivative has units liters/minute.', '函数值衡量水量，导数衡量该水量在局部的变化率，因此单位是升/分钟。'), commonMistake: t('“The tank contains −3 liters” confuses a rate with an amount. A negative derivative does not require a negative function value.', '“水箱有 −3 升水”混淆了变化率与水量。导数为负，并不要求函数值为负。'), reviewChapterId: 'derivatives' },
      { id: 'c-d4', prompt: t('D4 · Composite functions: differentiate with respect to x.', 'D4 · 复合函数：对 x 求导。'), equation: 'y=(2x+1)^3', answer: 'y′ = 6(2x + 1)²', explanation: t('The outer cube contributes 3(2x + 1)² and the inner function contributes a factor of 2.', '外层三次方给出 3(2x + 1)²，内层函数求导再给出因子 2。'), commonMistake: t('3(2x + 1)² differentiates only the outside. The input to the outside changes twice as fast as x, so multiply by 2.', '3(2x + 1)² 只对外层求导。外层的输入变化速度是 x 的两倍，因此还要乘以 2。'), reviewChapterId: 'chain-rule' },
      { id: 'c-d5', prompt: t('D5 · Accumulation: a volume changes at a constant −2 liters/minute for 3 minutes. What is its net change?', 'D5 · 累积：某水量连续 3 分钟以 −2 升/分钟的恒定速率变化。净变化量是多少？'), answer: t('−6 liters, meaning 6 liters were lost.', '−6 升，即减少了 6 升。'), explanation: t('Rate × duration gives change: (−2 liters/minute) × (3 minutes) = −6 liters.', '变化率乘时间等于变化量：(−2 升/分钟) × (3 分钟) = −6 升。'), commonMistake: t('−6 liters/minute keeps the rate units after multiplying by time. Minutes cancel. Also, this gives a change, not the final volume without an initial value.', '写成 −6 升/分钟，是乘以时间后仍保留了速率单位；分钟应约去。并且，这只是变化量，没有初始水量就无法得知最终水量。'), reviewChapterId: 'integrals' },
    ],
    routes: [
      { title: t('The algebra or the hole is the obstacle', '代数化简或“空点”有困难'), when: t('D1 or D2 was uncertain.', 'D1 或 D2 不确定。'), chapterId: 'limits', action: t('Begin with Chapter 1. If expansion or factoring is still the obstacle, use the algebra unit linked below before tackling difference quotients.', '从第 1 章开始。如果展开或因式分解仍有困难，先学习下方链接的代数单元，再处理差商。') },
      { title: t('You can compute but cannot interpret', '能计算，却解释不清含义'), when: t('D3 was wrong or lacked units.', 'D3 答错，或缺少单位。'), chapterId: 'derivatives', action: t('Use Chapter 2 to separate position, average rate, and instantaneous rate.', '用第 2 章区分位置、平均变化率与瞬时变化率。') },
      { title: t('Nested expressions lose a factor', '复合式求导容易漏因子'), when: t('D4 missed the inner derivative.', 'D4 漏掉内层导数。'), chapterId: 'chain-rule', action: t('Label the inner and outer functions in Chapter 3 before differentiating.', '在第 3 章中先标出内层与外层函数，再求导。') },
      { title: t('Rates and total changes are mixed up', '混淆变化率与总变化量'), when: t('D5 had the wrong sign, units, or interpretation.', 'D5 的符号、单位或解释有误。'), chapterId: 'integrals', action: t('Use Chapter 4 to distinguish signed accumulation, final amount, and total distance.', '用第 4 章区分带符号的累积量、最终量与总路程。') },
    ],
    chapters: [
      {
        id: 'limits', title: t('1. Ask what happens nearby, not only at the point', '1. 关注附近的趋势，而不只看该点'),
        goal: t('Use algebra and one-sided behavior to decide a finite two-sided limit.', '能结合代数与左右两侧趋势，判断有限的双侧极限。'),
        explanation: [
          t('The statement “f(x) approaches L as x approaches a” describes outputs for inputs arbitrarily close to a, with x different from a. It does not require f(a) to exist. More precisely, any prescribed positive error in the output can be met by taking every allowed input sufficiently close to a on the relevant side or sides.', '“x 趋近 a 时，f(x) 趋近 L”描述的是 x 与 a 不相等、但可以任意接近时的输出，并不要求 f(a) 存在。更精确地说，无论要求输出与 L 的误差有多小，只要所有允许的输入足够接近 a，就能满足该误差要求。'),
          t('A two-sided limit exists only when the left-hand and right-hand limits both exist and agree. A table suggests a trend but does not prove it; a graph can also hide a jump or a hole. Use an expression, a definition, or a valid limit rule to justify the conclusion.', '双侧极限存在，要求左极限与右极限都存在且相等。数表只能提示趋势，不能证明结论；图像也可能掩盖跳跃或空点。应使用表达式、定义或有效的极限法则说明理由。'),
          t('Polynomials are continuous, so their limits can be found by substitution. A quotient of continuous functions also permits substitution where its denominator is nonzero. If substitution produces 0/0, simplify or find another argument; do not treat 0/0 as the answer.', '多项式是连续的，因此可通过代入求极限。连续函数的商，在分母不为零时也可以直接代入。如果代入产生 0/0，应化简或寻找其他论证，不能把 0/0 当作答案。'),
        ],
        example: {
          diagram: 'removable-limit',
          title: t('A removable hole in a graph', '图像中的可去空点'), prompt: t('Find the limit and explain what happens to the graph at x = 3.', '求极限，并解释图像在 x = 3 处的情况。'), equation: '\\lim_{x\\to3}\\frac{x^2-9}{x-3}',
          steps: [
            { text: t('Substitution gives 0/0, which does not determine the limit. Factor the difference of squares.', '直接代入得到 0/0，尚不能确定极限。将平方差分解。'), equation: 'x^2-9=(x-3)(x+3)' },
            { text: t('For nearby x other than 3, cancel a nonzero common factor. This equality is restricted to x ≠ 3.', '在 3 附近但不等于 3 的位置，约去非零公因子。该等式仅在 x ≠ 3 时成立。'), equation: '\\frac{(x-3)(x+3)}{x-3}=x+3\\qquad(x\\ne3)' },
            { text: t('The nearby values agree with a continuous line. Evaluate its limit by substitution.', '邻近函数值与连续直线一致，因此对直线代入求极限。'), equation: '\\lim_{x\\to3}(x+3)=6' },
          ], conclusion: t('The limit is 6. The original graph is the line y = x + 3 with an open point at (3, 6). Assigning a new value f(3) = 6 would fill that hole and make a continuous extension, but the original quotient remains undefined at 3.', '极限为 6。原图像是直线 y = x + 3，但在 (3, 6) 处为空心点。如果另行定义 f(3) = 6，就能补上空点形成连续延拓；原来的分式本身仍在 3 处无定义。'),
        },
        pitfall: t('A hole and a jump are different. For |x|/x, inputs below 0 give −1 and inputs above 0 give 1. The two-sided limit at 0 does not exist, even though both one-sided limits do.', '空点与跳跃不同。对于 |x|/x，负输入给出 −1，正输入给出 1。虽然两侧极限各自存在，但在 0 处的双侧极限不存在。'),
        practice: [
          { id: 'c-1-1', prompt: t('Find the limit and state whether the original expression is defined at x = 5.', '求极限，并说明原式在 x = 5 时是否有定义。'), equation: '\\lim_{x\\to5}\\frac{x^2-25}{x-5}', answer: t('Limit 10; the original expression is undefined at 5.', '极限为 10；原式在 5 处无定义。'), explanation: t('Factor x² − 25 = (x − 5)(x + 5). For x ≠ 5, the quotient is x + 5, whose limit is 10.', '分解 x² − 25 = (x − 5)(x + 5)。当 x ≠ 5 时，分式等于 x + 5，其极限为 10。'), commonMistake: t('“No limit because the denominator is zero” confuses the value at the point with behavior nearby.', '“分母为零，所以极限不存在”混淆了该点函数值与邻近趋势。'), reviewChapterId: 'limits' },
          { id: 'c-1-2', prompt: t('Let f(x) = 2x for x < 1 and f(x) = x + 2 for x ≥ 1. Find the left-hand limit, right-hand limit, f(1), and the two-sided limit at 1.', '设 x < 1 时 f(x) = 2x，x ≥ 1 时 f(x) = x + 2。求 x = 1 处的左极限、右极限、f(1) 与双侧极限。'), answer: t('Left limit 2; right limit 3; f(1) = 3; the two-sided limit does not exist.', '左极限为 2，右极限为 3，f(1) = 3，双侧极限不存在。'), explanation: t('Use the formula for each side separately. The value f(1) comes from the second branch, but it cannot make the two unequal one-sided limits agree.', '分别使用对应一侧的公式。f(1) 由第二段公式确定，但该点的取值不能使两个不同的单侧极限变成相同。'), commonMistake: t('3 uses only the right-hand branch. A two-sided limit must account for inputs approaching from both directions.', '回答 3 只考虑了右侧分段。双侧极限必须同时考虑从两个方向趋近的输入。'), reviewChapterId: 'limits' },
        ],
        checkpoint: t('Before continuing, explain why a quotient can have a limit where it has no value, and why two different one-sided limits cannot form one two-sided limit.', '继续前，应能解释：为什么分式在无定义处仍可能有极限，以及为什么不同的单侧极限不能合成一个双侧极限。'),
        sources: [
          { title: t('OpenStax · Calculus Volume 1, §2.2: The Limit of a Function', 'OpenStax《微积分》第 1 卷，§2.2：函数的极限'), url: 'https://openstax.org/books/calculus-volume-1/pages/2-2-the-limit-of-a-function', use: t('Further examples of limits and one-sided behavior.', '进一步学习极限与单侧趋势的例子。'), language: t('English', '英语'), checkedAt: '2026-10-08' },
          { title: t('OpenStax · Calculus Volume 1, §1.1: Review of Functions', 'OpenStax《微积分》第 1 卷，§1.1：函数复习'), url: 'https://openstax.org/books/calculus-volume-1/pages/1-1-review-of-functions', use: t('Review function language and representations when prerequisites feel uncertain.', '函数基础不稳时，复习术语与表示方式。'), language: t('English', '英语'), checkedAt: '2026-10-08' },
        ],
      },
      {
        id: 'derivatives', title: t('2. Turn an average rate into an instantaneous rate', '2. 从平均变化率走向瞬时变化率'),
        goal: t('Build a derivative from its limit definition and keep rate units distinct from amount units.', '能从极限定义建立导数，并区分变化率单位与总量单位。'),
        explanation: [
          t('The average rate of change of f from a to a + h is [f(a + h) − f(a)]/h, where h ≠ 0. It is the slope of the secant line through two points. Its units are output units divided by input units.', 'f 从 a 到 a + h 的平均变化率为 [f(a + h) − f(a)]/h，其中 h ≠ 0。这是通过两个点的割线斜率，单位是输出单位除以输入单位。'),
          t('The derivative f′(a) is the limit of that quotient as h approaches 0, if a finite limit exists. It is the tangent slope and instantaneous rate. You do not substitute h = 0 into the original quotient; you analyze its nearby behavior.', '若 h 趋近 0 时该差商存在有限极限，这个极限就是导数 f′(a)，也就是切线斜率与瞬时变化率。不能直接把 h = 0 代入原差商，而应分析附近的趋势。'),
          t('The derivative also gives a local estimate: for small h, f(a + h) ≈ f(a) + f′(a)h. Multiply the rate at a by the input change, then add that estimated output change to the starting value. This is a tangent-line approximation; without further information, it gives no guaranteed error bound for a particular step size.', '导数还可以给出局部估计：当 h 很小时，f(a + h) ≈ f(a) + f′(a)h。把 a 处的变化率乘以输入变化量，再将估计的输出变化量加到初始值上。这称为切线近似；缺少更多信息时，不能保证某个具体步长对应的误差界。'),
          t('A function can be continuous and still have no derivative at a corner. At 0, |x| has left slope −1 and right slope 1, so there is no single derivative there. Differentiability is a stronger requirement than continuity.', '函数可以连续，却在尖点处不可导。例如 |x| 在 0 处左侧斜率为 −1，右侧斜率为 1，因此不存在唯一导数。可导比连续要求更强。'),
        ],
        example: {
          title: t('Position is not velocity', '位置不等于速度'), prompt: t('An object’s position is s(t) = t² − 4t + 7 meters, with time in seconds and t ≥ 0. Find its velocity at t = 3 using the definition. Compare it with its average velocity from t = 1 to t = 3.', '物体位置为 s(t) = t² − 4t + 7 米，时间单位为秒，且 t ≥ 0。用定义求 t = 3 时的速度，再与 t = 1 到 t = 3 的平均速度比较。'),
          steps: [
            { text: t('At t = 3, the position is 4 meters. Build the difference quotient around this point.', 't = 3 时位置为 4 米，围绕此点建立差商。'), equation: '\\frac{s(3+h)-s(3)}{h}=\\frac{(3+h)^2-4(3+h)+7-4}{h}' },
            { text: t('Expand, combine, and cancel h only while h ≠ 0.', '展开、合并，仅在 h ≠ 0 时约去 h。'), equation: '=\\frac{2h+h^2}{h}=2+h\\qquad(h\\ne0)' },
            { text: t('Take the limit to obtain instantaneous velocity, measured in meters per second.', '取极限得到瞬时速度，单位为米/秒。'), equation: 's^{\\prime}(3)=\\lim_{h\\to0}(2+h)=2' },
            { text: t('For the average over a fixed interval, use two positions instead. Here s(1) = s(3) = 4.', '固定区间上的平均速度，要使用两端位置。这里 s(1) = s(3) = 4。'), equation: '\\frac{s(3)-s(1)}{3-1}=\\frac{4-4}{2}=0' },
          ], conclusion: t('The instantaneous velocity at 3 seconds is +2 m/s, while the average velocity from 1 to 3 seconds is 0 m/s. The object can return to the same position over an interval while moving at its endpoint.', '第 3 秒的瞬时速度为 +2 米/秒，而第 1 秒到第 3 秒的平均速度为 0 米/秒。物体可以在一个区间内返回同一位置，同时在区间末端仍在运动。'),
        },
        pitfall: t('f′(a) = 0 does not by itself prove a maximum or minimum. For f(x) = x³, the derivative at 0 is zero, but the function increases through 0. A flat tangent is not automatically a turning point.', 'f′(a) = 0 本身不能证明极大值或极小值。例如 f(x) = x³ 在 0 处导数为零，但函数仍穿过该点继续递增。水平切线不一定意味着转折。'),
        practice: [
          { id: 'c-2-1', prompt: t('Use the definition to find f′(2), where f(x) = x² + 1.', '设 f(x) = x² + 1，用定义求 f′(2)。'), answer: 'f′(2) = 4', explanation: t('The quotient is [(2 + h)² + 1 − 5]/h = (4h + h²)/h = 4 + h for h ≠ 0. Its limit is 4.', '差商为 [(2 + h)² + 1 − 5]/h = (4h + h²)/h。当 h ≠ 0 时等于 4 + h，因此极限为 4。'), commonMistake: t('5 is f(2), the point’s height, not f′(2), the tangent slope.', '5 是 f(2)，也就是点的高度，而不是切线斜率 f′(2)。'), reviewChapterId: 'derivatives' },
          { id: 'c-2-2', prompt: t('A differentiable temperature function T has T(10) = 18 °C and T′(10) = −0.4 °C/min. Estimate T(10.5) with a tangent-line approximation and explain why it is an estimate.', '可导温度函数 T 满足 T(10) = 18 °C，T′(10) = −0.4 °C/分钟。用切线近似估计 T(10.5)，并说明为何只是估计值。'), answer: t('Approximately 17.8 °C.', '约为 17.8 °C。'), explanation: t('A small input change Δt = 0.5 gives approximate output change T′(10)Δt = −0.2 °C. Add it to 18. The derivative is local, and the actual cooling rate may change during the half minute.', '小时间变化 Δt = 0.5 对应近似温度变化 T′(10)Δt = −0.2 °C。加到 18 上得 17.8。导数描述局部变化率，实际降温速率在半分钟内可能变化。'), commonMistake: t('17.6 °C uses a full minute rather than half a minute. Claiming exactly 17.8 °C also assumes a constant rate that was not given.', '17.6 °C 错把半分钟当成一分钟。若声称精确等于 17.8 °C，则额外假定了题目并未给出的恒定变化率。'), reviewChapterId: 'derivatives' },
        ],
        checkpoint: t('Explain a derivative as a limit, a slope, and a rate with units. Then explain why average velocity can be zero while instantaneous velocity is nonzero.', '能从极限、斜率及带单位的变化率三个角度解释导数，并说明平均速度为零时，瞬时速度为何仍可能不为零。'),
        sources: [{ title: t('OpenStax · Calculus Volume 1, §3.1: Defining the Derivative', 'OpenStax《微积分》第 1 卷，§3.1：导数的定义'), url: 'https://openstax.org/books/calculus-volume-1/pages/3-1-defining-the-derivative', use: t('Further difference-quotient examples and the connection between tangent slopes and rates.', '补充差商例子，进一步联系切线斜率与变化率。'), language: t('English', '英语'), checkedAt: '2026-10-08' }],
      },
      {
        id: 'chain-rule', title: t('3. Track every layer of a changing input', '3. 跟踪每一层输入的变化'),
        goal: t('Differentiate a polynomial composition and use the result to build a tangent line.', '能对多项式复合函数求导，并用结果建立切线方程。'),
        explanation: [
          t('For a positive integer n, the derivative of xⁿ is nxⁿ⁻¹. Constants differentiate to 0; sums differentiate term by term; a constant multiplier stays in front. These rules are consequences of the limit definition and save repeating the expansion each time.', '对于正整数 n，xⁿ 的导数为 nxⁿ⁻¹。常数的导数为 0；和可以逐项求导；常数倍保留在前。这些法则来自极限定义，使我们不必每次都重新展开差商。'),
          t('For a composition y = F(g(x)), changes pass through two stages. If g is differentiable at x and F is differentiable at g(x), the chain rule gives y′ = F′(g(x))g′(x). Evaluate the outer derivative at the inner output, then multiply by the inner derivative.', '对于复合函数 y = F(g(x))，变化经过两个阶段。如果 g 在 x 处可导，F 在 g(x) 处可导，则链式法则给出 y′ = F′(g(x))g′(x)。先在内层输出处计算外层导数，再乘以内层导数。'),
          t('A tangent line at x = a needs both a point and a slope. The point is (a, f(a)); the slope is f′(a). Its equation is y − f(a) = f′(a)(x − a). It agrees with the function at a and models local change, but need not equal the function elsewhere.', 'x = a 处的切线需要一个点与一个斜率。点为 (a, f(a))，斜率为 f′(a)，因此方程是 y − f(a) = f′(a)(x − a)。它在 a 处经过函数图像，并刻画局部变化，但在别处通常不等于原函数。'),
        ],
        example: {
          title: t('Differentiate a fourth power, then find its tangent', '对四次方求导，再求切线'), prompt: t('Find the derivative of f(x) = (3x − 2)⁴ and the tangent line at x = 1.', '求 f(x) = (3x − 2)⁴ 的导数，以及 x = 1 处的切线。'),
          steps: [
            { text: t('Name the inner expression u = 3x − 2. Differentiate the outside with respect to u and the inside with respect to x.', '设内层表达式 u = 3x − 2。外层对 u 求导，内层对 x 求导。'), equation: '\\frac{d}{du}u^4=4u^3,\\qquad\\frac{du}{dx}=3' },
            { text: t('Multiply the two rates and replace u with its full expression.', '把两个变化率相乘，再把 u 换回完整表达式。'), equation: 'f^{\\prime}(x)=4(3x-2)^3\\cdot3=12(3x-2)^3' },
            { text: t('Find both the point and the slope at x = 1.', '求 x = 1 时的点与斜率。'), equation: 'f(1)=1,\\qquad f^{\\prime}(1)=12' },
            { text: t('Use point-slope form, keeping the tangent’s y distinct from the original formula.', '使用点斜式，注意切线的 y 不等于原函数公式。'), equation: 'y-1=12(x-1)\\quad\\Rightarrow\\quad y=12x-11' },
          ], conclusion: t('The derivative is 12(3x − 2)³, and the tangent line is y = 12x − 11. The line passes through (1, 1) and has slope 12; checking only one of these conditions is not enough.', '导数为 12(3x − 2)³，切线为 y = 12x − 11。该直线经过 (1, 1)，且斜率为 12；只检查其中一个条件还不够。'),
        },
        pitfall: t('A sum, product, quotient, and composition require different structures. For example, the derivative of x·x is 2x, not 1·1. Do not extend the term-by-term sum rule to multiplication; study the product and quotient rules next.', '和、积、商与复合具有不同结构。例如 x·x 的导数为 2x，而不是 1·1。不能把逐项求导的加法规则套用到乘法上；后续还需学习乘积与商的求导法则。'),
        practice: [
          { id: 'c-3-1', prompt: t('Differentiate and identify the inner derivative.', '求导，并指出内层导数。'), equation: 'y=(x^2+1)^3', answer: t('y′ = 6x(x² + 1)²; the inner derivative is 2x.', 'y′ = 6x(x² + 1)²；内层导数为 2x。'), explanation: t('The outer derivative is 3u² and u = x² + 1 has derivative 2x. Multiply them: 3(x² + 1)² × 2x.', '外层导数为 3u²，内层 u = x² + 1 的导数为 2x。相乘得 3(x² + 1)² × 2x。'), commonMistake: t('3(x² + 1)² omits the varying inner rate. 6x³ differentiates parts of the expression without respecting its composition.', '3(x² + 1)² 漏掉了变化的内层速率；6x³ 则把表达式拆开求导，忽略了复合结构。'), reviewChapterId: 'chain-rule' },
          { id: 'c-3-2', prompt: t('Find the tangent line to f(x) = x³ − 2x at x = 2.', '求 f(x) = x³ − 2x 在 x = 2 处的切线。'), answer: t('y − 4 = 10(x − 2), or y = 10x − 16', 'y − 4 = 10(x − 2)，即 y = 10x − 16'), explanation: t('f(2) = 8 − 4 = 4 and f′(x) = 3x² − 2, so f′(2) = 10. A line with that slope through (2, 4) has the stated equation.', 'f(2) = 8 − 4 = 4；f′(x) = 3x² − 2，因此 f′(2) = 10。过 (2, 4) 且斜率为 10 的直线即所求。'), commonMistake: t('y = 10x + 4 uses f(2) as a y-intercept. The known point is at x = 2, not x = 0.', 'y = 10x + 4 把 f(2) 当成了纵截距。已知点的横坐标是 2，而不是 0。'), reviewChapterId: 'chain-rule' },
        ],
        checkpoint: t('Mark the inner and outer functions before each chain-rule calculation. For a tangent line, verify both that it passes through the point and that its slope equals the derivative there.', '每次用链式法则前都标出内外层函数。求出切线后，同时检验它是否经过指定点，以及斜率是否等于该点导数。'),
        sources: [{ title: t('OpenStax · Calculus Volume 1, §3.6: The Chain Rule', 'OpenStax《微积分》第 1 卷，§3.6：链式法则'), url: 'https://openstax.org/books/calculus-volume-1/pages/3-6-the-chain-rule', use: t('More composition structures and chain-rule exercises after these polynomial examples.', '在本单元多项式例子之后，练习更多复合结构与链式法则。'), language: t('English', '英语'), checkedAt: '2026-10-08' }],
      },
      {
        id: 'integrals', title: t('4. Accumulate signed change and recover an amount', '4. 累积带符号的变化，并还原总量'),
        goal: t('Use a definite integral for net change and split at sign changes when finding total distance.', '能用定积分求净变化量，并在求总路程时按符号变化分段。'),
        explanation: [
          t('For a continuous rate r(t), divide a time interval into small pieces. A rectangle with height r(t) and width Δt estimates the change on one piece. The definite integral is the limit of the sum as the largest piece width tends to zero. Negative rates contribute negative changes.', '对于连续变化率 r(t)，把时间区间分成许多小段。高为 r(t)、宽为 Δt 的矩形估计一小段中的变化量。当最大小段宽度趋近零时，这些量之和的极限就是定积分。负变化率贡献负变化量。'),
          t('The Fundamental Theorem of Calculus connects this accumulation to derivatives. If r is continuous on [a, b] and F′ = r, then the integral from a to b of r equals F(b) − F(a). If A(x) is the integral from a to x of a continuous r(t), then A′(x) = r(x) at interior points.', '微积分基本定理把累积与导数联系起来。如果 r 在 [a, b] 上连续，且 F′ = r，那么 r 从 a 到 b 的积分等于 F(b) − F(a)。若 A(x) 为连续函数 r(t) 从 a 到 x 的积分，则在区间内部有 A′(x) = r(x)。'),
          t('A definite integral is a number with accumulated units, not a family of functions. An indefinite integral represents antiderivatives and includes an arbitrary constant. To recover a final amount from a rate, add the net change to the initial amount.', '定积分是具有累积量单位的数，不是一族函数。不定积分表示原函数族，需要包含任意常数。由变化率求最终量时，应把净变化量加到初始量上。'),
        ],
        example: {
          diagram: 'velocity-area',
          title: t('The same motion has two different totals', '同一运动，对应两种不同的总量'), prompt: t('An object has velocity v(t) = 2t − 4 m/s for 0 ≤ t ≤ 3 and initial position s(0) = 10 m. Find its displacement, final position, and total distance traveled.', '物体在 0 ≤ t ≤ 3 时的速度为 v(t) = 2t − 4 米/秒，初始位置 s(0) = 10 米。求位移、最终位置与总路程。'),
          steps: [
            { text: t('An antiderivative of 2t − 4 is t² − 4t. Evaluate at the upper endpoint minus the lower endpoint to find displacement.', '2t − 4 的一个原函数是 t² − 4t。用上端点值减去下端点值，得到位移。'), equation: '\\int_0^3(2t-4)\\,dt=[t^2-4t]_0^3=-3' },
            { text: t('Add displacement to the initial position. A negative displacement means motion ended 3 meters in the negative direction from the starting point.', '把位移加到初始位置上。负位移表示终点相对起点向负方向移动了 3 米。'), equation: 's(3)=10+(-3)=7' },
            { text: t('Distance counts movement in either direction positively. Find where velocity changes sign: t = 2. It is negative before 2 and positive after 2.', '路程把两个方向的运动都计为正。速度在 t = 2 处变号：此前为负，此后为正。'), equation: '\\int_0^3|2t-4|\\,dt=\\int_0^2(4-2t)\\,dt+\\int_2^3(2t-4)\\,dt' },
            { text: t('The two parts are 4 meters and 1 meter. Add their magnitudes, rather than canceling them.', '两段路程分别为 4 米与 1 米。将它们相加，而不是相互抵消。'), equation: '4+1=5\\text{ m}' },
          ], conclusion: t('Displacement is −3 m, final position is 7 m, and total distance is 5 m. The magnitude of the displacement is only 3 m because backward and forward motion partially cancel.', '位移为 −3 米，最终位置为 7 米，总路程为 5 米。位移大小只有 3 米，因为前后方向的运动部分抵消。'),
        },
        pitfall: t('The integral of a function is signed area, not automatically geometric area. Similarly, |∫v(t)dt| generally differs from ∫|v(t)|dt when velocity changes sign. Taking an absolute value only at the end cannot recover canceled motion.', '函数的定积分是带符号的面积，并不总是几何面积。同样，速度变号时，|∫v(t)dt| 一般不等于 ∫|v(t)|dt。只在最后取绝对值，无法还原已经抵消的运动。'),
        practice: [
          { id: 'c-4-1', prompt: t('Evaluate the definite integral and check the result by the area of a trapezoid.', '计算定积分，并用梯形面积检验。'), equation: '\\int_1^3(2x+1)\\,dx', answer: '10', explanation: t('Use F(x) = x² + x: F(3) − F(1) = 12 − 2 = 10. The graph has endpoint heights 3 and 7 and width 2, so the trapezoid area is (3 + 7) × 2/2 = 10.', '取 F(x) = x² + x，得 F(3) − F(1) = 12 − 2 = 10。图像两端高度为 3 与 7，宽为 2，梯形面积为 (3 + 7) × 2/2 = 10。'), commonMistake: t('12 evaluates only the upper endpoint. 10 + C treats a definite integral as an indefinite one; the endpoint subtraction removes the arbitrary constant.', '12 只计算了上端点。10 + C 则把定积分当成不定积分；两端相减后任意常数会消去。'), reviewChapterId: 'integrals' },
          { id: 'c-4-2', prompt: t('For this accumulation function, find A′(x) and A(2).', '对下列累积函数，求 A′(x) 与 A(2)。'), equation: 'A(x)=\\int_0^x(t^2+1)\\,dt', answer: 'A′(x) = x² + 1; A(2) = 14/3', explanation: t('The integrand is continuous, so the Fundamental Theorem gives A′(x) = x² + 1. Separately, A(2) = [t³/3 + t] from 0 to 2 = 8/3 + 2 = 14/3.', '被积函数连续，因此微积分基本定理给出 A′(x) = x² + 1。另行计算 A(2)：原函数 t³/3 + t 在 0 到 2 两端相减，得 8/3 + 2 = 14/3。'), commonMistake: t('x³/3 + x is A(x), not A′(x). The dummy variable t belongs inside the integral; the output derivative uses x.', 'x³/3 + x 是 A(x)，不是 A′(x)。积分变量 t 只在积分内部使用，输出导数应使用 x。'), reviewChapterId: 'integrals' },
        ],
        checkpoint: t('For any rate problem, write three labels before calculating: initial amount, net change, final amount. If the question asks for total distance or unsigned area, identify sign changes before integrating.', '每道变化率应用题开算前，先标出初始量、净变化量、最终量。如果要求总路程或不带符号的面积，积分前先找出变号点。'),
        sources: [
          { title: t('OpenStax · Calculus Volume 1, §5.2: The Definite Integral', 'OpenStax《微积分》第 1 卷，§5.2：定积分'), url: 'https://openstax.org/books/calculus-volume-1/pages/5-2-the-definite-integral', use: t('Explore signed area, sums, and definite-integral properties.', '继续学习带符号面积、求和与定积分性质。'), language: t('English', '英语'), checkedAt: '2026-10-08' },
          { title: t('OpenStax · Calculus Volume 1, §5.3: The Fundamental Theorem of Calculus', 'OpenStax《微积分》第 1 卷，§5.3：微积分基本定理'), url: 'https://openstax.org/books/calculus-volume-1/pages/5-3-the-fundamental-theorem-of-calculus', use: t('Study the theorem’s hypotheses and further accumulation-function examples.', '继续学习定理条件与累积函数的例子。'), language: t('English', '英语'), checkedAt: '2026-10-08' },
        ],
      },
    ],
    masteryIntro: t('Work these without viewing the examples. Include the domain or interval, units where relevant, and the reason your method applies. These test connections across chapters rather than speed.', '不看例题完成以下题目。写出定义域或区间、适用单位，以及方法成立的理由。这些题检查章节之间的联系，不考速度。'),
    mastery: [
      { id: 'c-m1', prompt: t('Find the limit and explain whether the original function is continuous at x = 4.', '求极限，并解释原函数在 x = 4 处是否连续。'), equation: '\\lim_{x\\to4}\\frac{x^2-16}{x-4}', answer: t('The limit is 8. The original function is not continuous at 4 because it is not defined there.', '极限为 8。原函数在 4 处无定义，因此在该点不连续。'), explanation: t('For x ≠ 4, the quotient equals x + 4. Its limit is 8. Continuity also requires a defined value f(4) equal to that limit, which the original rule lacks.', '当 x ≠ 4 时，分式等于 x + 4，其极限为 8。连续还要求 f(4) 有定义且等于该极限，而原规则没有这个值。'), commonMistake: t('“It is continuous because the limit exists” omits the function-value requirement.', '“极限存在，所以连续”漏掉了对该点函数值的要求。'), reviewChapterId: 'limits' },
      { id: 'c-m2', prompt: t('For f(x) = (2x + 1)³, find f′(1) and the tangent line at x = 1. Use that line to estimate f(1.01).', '设 f(x) = (2x + 1)³，求 f′(1) 与 x = 1 处的切线，再用切线估计 f(1.01)。'), answer: t('f′(1) = 54; y − 27 = 54(x − 1); f(1.01) ≈ 27.54.', 'f′(1) = 54；y − 27 = 54(x − 1)；f(1.01) ≈ 27.54。'), explanation: t('The chain rule gives f′(x) = 6(2x + 1)². At x = 1 the value is 27 and the slope is 54. A change of 0.01 adds approximately 54 × 0.01 = 0.54.', '链式法则给出 f′(x) = 6(2x + 1)²。x = 1 时函数值为 27，斜率为 54。输入变化 0.01 时，输出近似增加 54 × 0.01 = 0.54。'), commonMistake: t('27.27 misses the inner factor 2. Giving 27.54 as exact forgets that a tangent line is a local approximation to this curved graph.', '27.27 漏掉了内层因子 2。把 27.54 当作精确值，则忘记切线只是曲线的局部近似。'), reviewChapterId: 'chain-rule' },
      { id: 'c-m3', prompt: t('An object has v(t) = 3t − 6 m/s on 0 ≤ t ≤ 4 and s(0) = 5 m. Find displacement, final position, and total distance. Explain why one can be zero.', '物体在 0 ≤ t ≤ 4 时速度为 v(t) = 3t − 6 米/秒，且 s(0) = 5 米。求位移、最终位置与总路程，并解释其中一个量为什么可以为零。'), answer: t('Displacement 0 m; final position 5 m; total distance 12 m.', '位移为 0 米，最终位置为 5 米，总路程为 12 米。'), explanation: t('Integrating v gives [1.5t² − 6t] from 0 to 4 = 0. Velocity is negative until t = 2, then positive. The two intervals contribute −6 m and +6 m of displacement, so they cancel; their distances add to 12 m.', '积分得 [1.5t² − 6t] 在 0 到 4 两端相减，结果为 0。速度在 t = 2 之前为负，之后为正。两段位移为 −6 米与 +6 米，抵消后为零；路程则相加为 12 米。'), commonMistake: t('“Distance is zero because the integral is zero” counts cancellation as no movement. Total distance integrates speed, the absolute value of velocity.', '“积分为零，所以路程为零”把抵消误当作没有运动。总路程应积分速率，即速度的绝对值。'), reviewChapterId: 'integrals' },
    ],
    masteryRule: t('Move on when you can solve all three independently and explain the distinction in each: limit versus value, value versus derivative, and displacement versus distance. If a distinction is still unclear, revisit the linked chapter and solve a new version later. This is a learning checkpoint, not a certification of course or exam readiness.', '当你能独立完成 3 题，并解释其中的区别：极限与函数值、函数值与导数、位移与路程，再继续学习。若有区别仍不清楚，返回对应章节，稍后完成一道变式题。这是学习检查点，不代表通过整门课程或已具备考试准备度。'),
    nextSteps: [
      { title: t('Repair algebra before adding more rules', '增加新法则前，先补齐代数'), body: t('If expansion, fractions, equations, or function inputs caused the mistakes, strengthen those first. Calculus rules become easier to use when the algebra no longer hides the concept.', '若错误来自展开、分数、方程或函数输入，先巩固这些基础。代数不再遮蔽概念时，微积分法则会更容易运用。'), href: '/guides/algebra-foundations', linkLabel: t('Open the algebra learning unit', '进入代数学习单元') },
      { title: t('Continue through a complete first course', '继续学习完整的入门课程'), body: t('Next study product and quotient rules, trigonometric and exponential derivatives, derivative applications, and substitution for integrals. Follow a coherent textbook or course. Series belong to a later stage after the basic ideas of differentiation and integration are secure.', '接下来学习乘积与商的求导法则，三角与指数函数求导，导数应用，以及换元积分。选择一本结构连贯的教材或一门完整课程。级数应放在更后阶段，先掌握微分与积分的基本思想。'), href: '/resources?topic=calculus', linkLabel: t('Compare calculus resources', '比较微积分资源') },
    ],
    editorialNote: t('The explanations and exercises in this unit are original OnlyMath learning material. Linked textbook sections provide optional further reading; their inclusion does not imply endorsement. English and Simplified Chinese cover the same questions and learning goals. Link checks were performed on October 8, 2026; external pages can change.', '本单元的讲解与练习为 OnlyMath 原创学习内容。链接教材章节仅供延伸阅读，不代表对方认可或背书。英语与简体中文包含相同的题目和学习目标。外部链接于 2026 年 10 月 8 日核查，原站内容此后可能变化。'),
  }
}
